# permissions for end users to view distexecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distexec-viewer-role
rules:
- apiGroups:
  - exec.yuhong.test
  resources:
  - distexecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exec.yuhong.test
  resources:
  - distexecs/status
  verbs:
  - get
