---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - exec.yuhong.test
  resources:
  - distexecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exec.yuhong.test
  resources:
  - distexecs/finalizers
  verbs:
  - update
- apiGroups:
  - exec.yuhong.test
  resources:
  - distexecs/status
  verbs:
  - get
  - patch
  - update
